project_id = "phkzxeajzglbmaymvtmt"

[functions.admin-create-user]
verify_jwt = false

[functions.admin-update-user]
verify_jwt = false

[functions.seat-capacity]
verify_jwt = false

[functions.seat-usage]
verify_jwt = false

[functions.seat-request]
verify_jwt = false

[functions.razorpay-webhook]
verify_jwt = false
